import { createContext, useContext, useState } from 'react';

const translations = {
  EN: {
    // Navigation
    home: "Home",
    insights: "Insights",
    circle: "Circle",
    artisans: "Artisans",
    my_bookings: "My Bookings",

    // Home
    welcome_back: "Welcome back",
    madame_kim: "Madame Kim",
    ai_concierge: "Consultation Inquiry",
    ai_msg: "Have questions? Feel free to ask anytime.",
    start_conv: "Start Consultation",
    schedule: "Upcoming Schedule",
    view_all: "VIEW ALL",
    month_nov: "NOV",
    assessment: "Anti-Aging Assessment",
    dr_lee_clinic: "Dr. Lee's Artisan Clinic (VIP Suite)",
    curated: "Curated For You",
    stem_cell: "Stem Cell Renewal",
    invite_only: "INVITATION ONLY",
    signature_lift: "Signature Lifting",
    dr_choi_ex: "DR. CHOI EXCLUSIVE",
    services: "Medical Services",

    // Categories
    cat_dental: "Dental",
    cat_eye: "Ophthalmology",
    cat_derma: "Dermatology",
    cat_plastic: "Plastic Surgery",
    cat_other: "Others",
    cat_all: "All",

    // Insights
    med_art: "Medical Artistry",
    curated_col: "CURATED EXPERT COLUMNS",
    read_time_5: "5 min read",
    read_time_8: "8 min read",
    read_time_4: "4 min read",
    insight_cat_1: "AESTHETIC INNOVATION",
    insight_title_1: "The Architecture of Facial Harmony: Beyond Symmetry",
    insight_author_1: "Dr. Park Min-ho",
    insight_cat_2: "REGENERATIVE MED",
    insight_title_2: "Cellular Time-Reversal: The Future of Exosomes",
    insight_author_2: "Dr. Lee Jin-hee",
    insight_cat_3: "VVIP LIFESTYLE",
    insight_title_3: "Post-Procedure Recovery in the Presidential Suite",
    insight_author_3: "The Seoul Private Editorial",

    // Circle
    inner_circle: "Inner Circle",
    invite_forum: "INVITE-ONLY FORUM",
    verified: "VERIFIED ONLY",
    reply: "Reply Privately",
    endorsements: "Endorsements",
    post_time_1: "2 hours ago",
    post_content_1: "Just completed the Signature Contour protocol with Dr. Choi. The recovery suite service was impeccable. Highly recommend requesting the private airport transfer—it made the arrival seamless.",
    post_time_2: "5 hours ago",
    post_content_2: "Can anyone share their experience with the new exosome therapy at Artisan Clinic? Looking for genuine feedback before my consultation next week.",

    // Artisans
    med_artisans: "Medical Artisans",
    masters: "THE MASTERS OF CRAFT",
    filter: "FILTER",
    logistics: "LOGISTICS:",
    suites_avail: "Suite Available",
    waitlist: "Waitlist Only",
    reserve: "Reserve",
    no_artisans: "No artisans found for this category.",
    concierge_filters: "Concierge Filters",
    vvip_pickup: "VVIP Pick-up Zone",
    region_all: "All Regions",
    region_pnh: "Phnom Penh Private Airport (PNH)",
    region_icn: "Incheon VIP Terminal (ICN)",
    region_sgbac: "Gimpo Business Aviation Center (SGBAC)",
    apply_pref: "Apply Preferences",
    dr_choi: "Dr. Choi Woo-jin",
    dr_choi_spec: "Facial Contouring Artisan",
    dr_choi_mile: "20+ Years Global Expertise • 10,000+ Cases",
    dr_park: "Dr. Park Seo-yeon",
    dr_park_spec: "Anti-Aging & Stem Cell",
    dr_park_mile: "Harvard Medical Fellowship • Pioneer in Exosomes",

    // Auth
    awaiting: "AWAITING IDENTIFICATION",
    vvip_member: "VVIP MEMBER",
    authenticate: "AUTHENTICATE",
    verifying: "VERIFYING IDENTITY",
    social_login: "OR CONTINUE WITH",
    powered_by: "POWERED BY",

    // Chatbot & Concierge
    chat_online: "AI Consultant Online",
    chat_type: "Type your inquiry...",
    chat_send: "Send",
    chat_connecting: "Connecting to medical staff...",
    chat_reply: "I have arranged the Maybach for your arrival at ICN. Is there anything else you need?",
    concierge_title: "VVIP Lifestyle Services",
    concierge_sub: "BESPOKE REQUESTS",
    srv_fasttrack: "Airport Fast-Track",
    srv_limo: "Limousine & Maybach Pickup",
    srv_hotel: "5-Star Hotel Recovery Suite",
    srv_diet: "Post-Surgery Customized Diet",
    btn_request: "Request",

    // Phase 3
    passport_title: "Medical E-Wallet",
    passport_id: "DIGITAL IDENTITY",
    passport_records: "Secure Medical Records",
    scan_3d: "3D Facial Scan (NOV 2026)",
    xray_pano: "Panoramic X-Ray",
    tryon_title: "Virtual AI Assessment",
    tryon_scanning: "Scanning Facial Symmetry...",
    tryon_sym: "Symmetry Match",
    tryon_age: "Estimated Skin Age",
    wiz_title: "Booking Concierge",
    wiz_step1: "Select Date",
    wiz_step2: "Logistics",
    wiz_step_hotel: "Accommodation",
    wiz_step3: "Interpreter",
    wiz_step4: "Signature",
    wiz_confirm: "Confirm Reservation",
    log_hotel_title: "Hotel Request (5-Star)",
    log_hotel_sub: "Luxury Partner Hotels",
    log_hotel_detail: "We will arrange a premium stay at one of our partner 5-star hotels (Four Seasons, Shilla, or Grand InterContinental). Includes medical-optimized room service.",
    log_hotel_self_title: "Self Booking",
    log_hotel_self_sub: "Independent stay",
    log_hotel_self_detail: "Choose your own accommodation. Please ensure your location is within 30 minutes of the clinic for post-procedure check-ups.",
    my_page_title: "My Page",
    my_points: "My Points",
    my_coupons: "My Coupons",
    my_inquiries: "Inquiries",
    my_level: "Lv.1",
    my_bookings_pay: "Bookings & Payments",
    my_liked: "Liked List",
    my_benefits: "Benefits",
    my_reviews: "Reviews",
    my_notif: "Notifications",
    my_msgs: "Messages",
    cust_center: "Customer Center",
    notice: "Notice",
    settings_title: "Settings",
    service_info: "Service Information",
    version_info: "Version Info",
    partnership: "Partnership & Ads",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    location_terms: "Location Terms",
    notif_settings: "Notification Settings",
    gen_notif: "General Notifications",
    notes_notif: "Note Notifications",
    marketing_info: "Marketing Information",
    push: "Push",
    night_push: "Night Push (21:00 - 08:00)",
    acc_mgmt: "Account Management",
    logout: "Logout",
    delete_acc: "Delete Account",
    upload_profile: "Upload Profile Image",
    confirmed_res: "Confirmed Reservation",
    no_bookings: "No confirmed bookings yet.",
    voice_listening: "Listening...",
    voice_tap: "Tap to Speak",

    // Phase 4
    est_title: "Price Estimator",
    est_sub: "Transparent Pricing",
    est_proc1: "Signature Anti-Aging",
    est_proc2: "Stem Cell Therapy",
    est_proc3: "Premium Dental Implant",
    est_total: "Estimated Cost",
    ba_title: "Clinical Excellence",
    ba_sub: "Drag to compare",
    time_arrive: "ICN Arrival",
    time_consult: "Consultation",
    time_surgery: "Procedure",
    time_recover: "Recovery Room",

    // Phase 5: Clinics Pivot
    clinics_title: "Clinics",
    clinics_sub: "Verified Partners",
    reviews_count: "reviews",
    clinic_1: "Grand Plastic Surgery",
    clinic_2: "Seoul National Dental",
    proc_1: "Signature Stem Cell Anti-Aging Lift",
    proc_2: "3D Premium Implant & Whitening",
    clinic_3: "The Seoul Breast Clinic",
    clinic_4: "Iconic Rhinoplasty Center",
    proc_3: "Full HD Premium Breast Augmentation",
    proc_4: "Structural Nose Reshaping & Contour",
    about_procedure: "About Procedure",
    duration: "Duration",
    recovery: "Recovery",
    medical_staff: "Medical Staff",
    location: "Location",
    reserve_now: "Reserve Now",
    back_to_list: "Back to List",
    log_vip_title: "ICN VIP Terminal Pickup",
    log_vip_escort: "and escort $680",
    log_vip_car: "Maybach S680",
    log_vip_detail: "Exclusive Maybach S680 pickup directly from the ICN VIP Gate. Includes personal concierge escort through immigration, 3 hours of chauffeur service, and luggage handling.",
    log_self_title: "Self Arrival",
    log_self_sub: "Independent transport",
    log_self_detail: "Arrange your own transportation to the clinic. We will provide the exact GPS coordinates and contact details of your dedicated medical coordinator upon arrival."
  },
  KO: {
    home: "홈",
    insights: "인사이트",
    circle: "서클",
    artisans: "아티잔",
    my_bookings: "내 예약",

    welcome_back: "환영합니다",
    madame_kim: "김 마담님",
    ai_concierge: "상담문의",
    ai_msg: "궁금한게 있으신가요? 언제든 문의해주세요.",
    start_conv: "상담 시작하기",
    schedule: "예정된 일정",
    view_all: "전체 보기",
    month_nov: "11월",
    assessment: "안티에이징 진단",
    dr_lee_clinic: "이원장 아티잔 클리닉 (VIP 스위트)",
    curated: "맞춤형 큐레이션",
    stem_cell: "줄기세포 리뉴얼",
    invite_only: "초청자 전용",
    signature_lift: "시그니처 리프팅",
    dr_choi_ex: "최원장 익스클루시브",
    services: "의료 서비스",

    cat_dental: "치과",
    cat_eye: "안과",
    cat_derma: "피부과",
    cat_plastic: "성형외과",
    cat_other: "기타",
    cat_all: "전체",

    med_art: "메디컬 아티스트리",
    curated_col: "전문가 칼럼 큐레이션",
    read_time_5: "5분 소요",
    read_time_8: "8분 소요",
    read_time_4: "4분 소요",
    insight_cat_1: "미용 혁신",
    insight_title_1: "안면 조화의 건축학: 대칭을 넘어서",
    insight_author_1: "박민호 원장",
    insight_cat_2: "재생 의학",
    insight_title_2: "세포 시간 역행: 엑소좀의 미래",
    insight_author_2: "이진희 원장",
    insight_cat_3: "VVIP 라이프스타일",
    insight_title_3: "프레지덴셜 스위트에서의 시술 후 회복",
    insight_author_3: "The Seoul Private 편집부",

    inner_circle: "프라이빗 서클",
    invite_forum: "초청자 전용 포럼",
    verified: "인증 회원",
    reply: "비밀 답글",
    endorsements: "추천",
    post_time_1: "2시간 전",
    post_content_1: "최원장님께 시그니처 윤곽 수술을 방금 마쳤습니다. 회복실 서비스가 정말 완벽했어요. 프라이빗 공항 픽업 서비스는 꼭 신청하시길 강력히 추천합니다.",
    post_time_2: "5시간 전",
    post_content_2: "아티잔 클리닉에서 새로 나온 엑소좀 테라피 받아보신 분 계신가요? 다음 주 상담 전에 실제 후기가 궁금합니다.",

    med_artisans: "메디컬 아티잔",
    masters: "마스터 아티잔",
    filter: "필터",
    logistics: "로지스틱스:",
    suites_avail: "스위트룸 예약 가능",
    waitlist: "대기 명단 등록",
    reserve: "예약하기",
    no_artisans: "해당 카테고리의 아티잔이 없습니다.",
    concierge_filters: "컨시어지 필터",
    vvip_pickup: "VVIP 픽업 존",
    region_all: "모든 지역",
    region_pnh: "프놈펜 프라이빗 공항 (PNH)",
    region_icn: "인천공항 VIP 터미널 (ICN)",
    region_sgbac: "김포 비즈니스 항공 센터 (SGBAC)",
    apply_pref: "환경설정 적용",
    dr_choi: "최우진 원장",
    dr_choi_spec: "안면 윤곽 마스터",
    dr_choi_mile: "20년 이상 글로벌 경력 • 10,000건 이상 집도",
    dr_park: "박서연 원장",
    dr_park_spec: "안티에이징 & 줄기세포",
    dr_park_mile: "하버드 의대 펠로우십 • 엑소좀 파이오니어",

    awaiting: "신원 확인 대기 중",
    vvip_member: "VVIP 멤버",
    authenticate: "생체 인증",
    verifying: "신원 확인 중",
    social_login: "소셜 계정으로 로그인",
    powered_by: "제공:",

    chat_online: "AI 상담원 연결됨",
    chat_type: "문의 내용을 입력하세요...",
    chat_send: "전송",
    chat_connecting: "의료진에게 연결 중입니다...",
    chat_reply: "인천공항 도착 시 탑승하실 마이바흐 배차를 완료했습니다. 더 필요하신 서비스가 있으신가요?",
    concierge_title: "VVIP 라이프스타일 서비스",
    concierge_sub: "맞춤형 비스포크 요청",
    srv_fasttrack: "공항 패스트트랙",
    srv_limo: "리무진 & 마이바흐 픽업",
    srv_hotel: "5성급 호텔 회복실",
    srv_diet: "수술 후 맞춤형 식단 케어",
    btn_request: "요청하기",

    passport_title: "메디컬 E-Wallet",
    passport_id: "디지털 신원 확인",
    passport_records: "보안 의료 기록",
    scan_3d: "3D 안면 스캔 (2026년 11월)",
    xray_pano: "파노라마 X-Ray",
    tryon_title: "가상 AI 안면 분석",
    tryon_scanning: "안면 대칭 스캔 중...",
    tryon_sym: "안면 대칭률",
    tryon_age: "예측 피부 연령",
    wiz_title: "부킹 컨시어지",
    wiz_step1: "날짜 선택",
    wiz_step2: "차량 배차",
    wiz_step_hotel: "숙소 선택",
    wiz_step3: "전담 통역",
    wiz_step4: "전자 서명",
    wiz_confirm: "예약 확정",
    log_hotel_title: "5성급 호텔 예약 요청",
    log_hotel_sub: "파트너사 럭셔리 호텔",
    log_hotel_detail: "포시즌스, 신라, 그랜드 인터컨티넨탈 등 파트너 5성급 호텔 중 최적의 객실을 예약해 드립니다. 시술 후 회복에 최적화된 메디컬 룸서비스가 제공됩니다.",
    log_hotel_self_title: "직접 예약",
    log_hotel_self_sub: "개별 숙소 이용",
    log_hotel_self_detail: "직접 숙소를 예약하시는 옵션입니다. 원활한 사후 관리를 위해 병원에서 30분 이내 거리에 머무시는 것을 권장합니다.",
    my_page_title: "마이페이지",
    my_points: "내 포인트",
    my_coupons: "내 쿠폰",
    my_inquiries: "채팅상담",
    my_level: "Lv.1",
    my_bookings_pay: "내 예약 · 결제 내역",
    my_liked: "찜 목록",
    my_benefits: "혜택",
    my_reviews: "후기",
    my_notif: "알림",
    my_msgs: "메시지",
    cust_center: "고객센터",
    notice: "공지사항",
    settings_title: "설정",
    service_info: "서비스 안내",
    version_info: "버전정보",
    partnership: "제휴 및 광고문의",
    terms: "이용약관",
    privacy: "개인정보처리방침",
    location_terms: "위치기반서비스 이용약관 동의",
    notif_settings: "알림설정",
    gen_notif: "일반 알림",
    notes_notif: "쪽지 알림",
    marketing_info: "마케팅 정보 수신",
    push: "푸시",
    night_push: "야간 푸시(오후 9시~오전 8시)",
    acc_mgmt: "계정관리",
    logout: "로그아웃",
    delete_acc: "회원 탈퇴",
    upload_profile: "프로필 사진 업로드",
    confirmed_res: "확정된 예약",
    no_bookings: "확정된 예약 내역이 없습니다.",
    voice_listening: "듣고 있습니다...",
    voice_tap: "눌러서 말하기",

    est_title: "예상 견적 계산기",
    est_sub: "투명한 비용 안내",
    est_proc1: "시그니처 안티에이징",
    est_proc2: "줄기세포 테라피",
    est_proc3: "프리미엄 치과 임플란트",
    est_total: "예상 총 비용",
    ba_title: "임상 케이스 갤러리",
    ba_sub: "드래그하여 비교하기",
    time_arrive: "인천공항 입국",
    time_consult: "전문의 상담",
    time_surgery: "수술 진행",
    time_recover: "VIP 회복실 입원",

    clinics_title: "클리닉 & 시술",
    clinics_sub: "공식 파트너 병원",
    reviews_count: "리뷰",
    clinic_1: "그랜드 성형외과",
    clinic_2: "서울 내셔널 치과",
    proc_1: "시그니처 줄기세포 안티에이징 리프팅",
    proc_2: "3D 프리미엄 임플란트 및 미백",
    clinic_3: "더 서울 유방외과",
    clinic_4: "아이코닉 코성형 센터",
    proc_3: "Full HD 프리미엄 가슴 성형",
    proc_4: "구조적 코 성형 및 윤곽",
    about_procedure: "시술 정보",
    duration: "소요 시간",
    recovery: "회복 기간",
    medical_staff: "의료진",
    location: "위치",
    reserve_now: "예약하기",
    back_to_list: "목록으로",
    log_vip_title: "인천공항 VIP 터미널 픽업",
    log_vip_escort: "에스코트 포함 $680",
    log_vip_car: "마이바흐 S680",
    log_vip_detail: "인천공항 VIP 게이트에서 전용 마이바흐 S680으로 픽업해 드립니다. 입국 심사 패스트트랙 에스코트, 3시간 쇼퍼 서비스, 수하물 핸들링 서비스가 포함되어 있습니다.",
    log_self_title: "자가 도착",
    log_self_sub: "개별 이동",
    log_self_detail: "병원을 직접 방문하시는 옵션입니다. 예약 확정 시 담당 의료 코디네이터의 연락처와 구글 맵 좌표를 보내드립니다."
  },
  KM: {
    home: "ទំព័រដើម",
    insights: "ការយល់ដឹង",
    circle: "រង្វង់ឯកជន",
    artisans: "គ្រូពេទ្យជំនាញ",
    my_bookings: "ការកក់របស់ខ្ញុំ",

    welcome_back: "សូមស្វាគមន៍មកវិញ",
    madame_kim: "Madame Kim",
    ai_concierge: "ការសាកសួរពិគ្រោះយោបល់",
    ai_msg: "តើអ្នកមានសំណួរទេ? សូមកុំស្ទាក់ស្ទើរក្នុងការសួរគ្រប់ពេល។",
    start_conv: "ចាប់ផ្តើមការពិគ្រោះយោបល់",
    schedule: "កាលវិភាគបន្ទាប់",
    view_all: "មើលទាំងអស់",
    month_nov: "វិច្ឆិកា",
    assessment: "ការវាយតម្លៃប្រឆាំងភាពចាស់",
    dr_lee_clinic: "គ្លីនិកគ្រូពេទ្យ Lee (បន្ទប់ VIP)",
    curated: "ជ្រើសរើសសម្រាប់អ្នក",
    stem_cell: "ការបន្តកោសិការ",
    invite_only: "សម្រាប់តែអ្នកដែលត្រូវបានអញ្ជើញ",
    signature_lift: "ការលើកស្បែកមុខ",
    dr_choi_ex: "ផ្តាច់មុខដោយគ្រូពេទ្យ Choi",
    services: "សេវាកម្មវេជ្ជសាស្រ្ត",

    cat_dental: "ទន្តសាស្រ្ត",
    cat_eye: "ចក្ខុរោគ",
    cat_derma: "រោគសើស្បែក",
    cat_plastic: "ការវះកាត់កែសម្ផស្ស",
    cat_other: "ផ្សេងៗ",
    cat_all: "ទាំងអស់",

    med_art: "សិល្បៈវេជ្ជសាស្រ្ត",
    curated_col: "អត្ថបទអ្នកជំនាញ",
    read_time_5: "អាន ៥ នាទី",
    read_time_8: "អាន ៨ នាទី",
    read_time_4: "អាន ៤ នាទី",
    insight_cat_1: "ការច្នៃប្រឌិតសោភ័ណភាព",
    insight_title_1: "ស្ថាបត្យកម្មនៃភាពសុខដុមនៃផ្ទៃមុខ",
    insight_author_1: "វេជ្ជបណ្ឌិត Park Min-ho",
    insight_cat_2: "វេជ្ជសាស្ត្របង្កើតឡើងវិញ",
    insight_title_2: "ការត្រលប់ពេលវេលាកោសិកា",
    insight_author_2: "វេជ្ជបណ្ឌិត Lee Jin-hee",
    insight_cat_3: "របៀបរស់នៅ VVIP",
    insight_title_3: "ការងើបឡើងវិញក្រោយនីតិវិធី",
    insight_author_3: "កម្មវិធីកែសម្រួលទីក្រុងសេអ៊ូល",

    inner_circle: "រង្វង់ឯកជន",
    invite_forum: "វេទិកាសម្រាប់តែអ្នកអញ្ជើញ",
    verified: "បានផ្ទៀងផ្ទាត់",
    reply: "ឆ្លើយតបជាឯកជន",
    endorsements: "ការគាំទ្រ",
    post_time_1: "២ ម៉ោងមុន",
    post_content_1: "ទើបតែបញ្ចប់ពិធីការវះកាត់ជាមួយគ្រូពេទ្យ Choi។ ការស្នាក់នៅគឺល្អឥតខ្ចោះ។",
    post_time_2: "៥ ម៉ោងមុន",
    post_content_2: "តើមាននរណាម្នាក់អាចចែករំលែកបទពិសោធន៍របស់ពួកគេជាមួយការព្យាបាលកោសិកាថ្មីនៅគ្លីនិកអត់? ខ្ញុំកំពុងស្វែងរកមតិកែលម្អពិតប្រាកដមុនពេលពិគ្រោះយោបល់នៅសប្តាហ៍ក្រោយ។",

    med_artisans: "គ្រូពេទ្យជំនាញ",
    masters: "កំពូលអ្នកជំនាញ",
    filter: "តម្រង",
    logistics: "ការដឹកជញ្ជូន:",
    suites_avail: "មានបន្ទប់ VIP",
    waitlist: "បញ្ជីរង់ចាំ",
    reserve: "កក់ឥឡូវនេះ",
    no_artisans: "រកមិនឃើញសិប្បករសម្រាប់ប្រភេទនេះទេ។",
    concierge_filters: "តម្រងសេវាកម្មជំនួយ",
    vvip_pickup: "តំបន់ទៅយក VVIP",
    region_all: "តំបន់ទាំងអស់",
    region_pnh: "អាកាសយានដ្ឋានឯកជនភ្នំពេញ (PNH)",
    region_icn: "ស្ថានីយ VIP Incheon (ICN)",
    region_sgbac: "មជ្ឈមណ្ឌលអាកាសចរណ៍អាជីវកម្ម Gimpo (SGBAC)",
    apply_pref: "អនុវត្តចំណូលចិត្ត",
    dr_choi: "វេជ្ជបណ្ឌិត Choi Woo-jin",
    dr_choi_spec: "អ្នកជំនាញកាត់ទម្រង់មុខ",
    dr_choi_mile: "បទពិសោធន៍សកល ២០+ ឆ្នាំ • ១ម៉ឺន+ ករណី",
    dr_park: "វេជ្ជបណ្ឌិត Park Seo-yeon",
    dr_park_spec: "ប្រឆាំងភាពចាស់ & កោសិកាដើម",
    dr_park_mile: "សមាគមវេជ្ជសាស្ត្រ Harvard • អ្នកត្រួសត្រាយផ្លូវនៅ Exosomes",

    awaiting: "រង់ចាំការបញ្ជាក់អត្តសញ្ញាណ",
    vvip_member: "សមាជិក VVIP",
    authenticate: "បញ្ជាក់អត្តសញ្ញាណ",
    verifying: "កំពុងផ្ទៀងផ្ទាត់...",
    social_login: "ចូលដោយគណនីសង្គម",
    powered_by: "ឧបត្ថម្ភដោយ",

    chat_online: "សេវាកម្មជំនួយ AI តាមអ៊ីនធឺណិត",
    chat_type: "វាយបញ្ចូលសំណើរបស់អ្នក...",
    chat_send: "បញ្ជូន",
    chat_connecting: "កំពុងភ្ជាប់ទៅកាន់បុគ្គលិកពេទ្យ...",
    chat_reply: "ខ្ញុំបានរៀបចំរថយន្ត Maybach សម្រាប់ការមកដល់របស់អ្នកនៅ ICN។ តើមានអ្វីផ្សេងទៀតដែលអ្នកត្រូវការទេ?",
    concierge_title: "សេវាកម្មរបៀបរស់នៅ VVIP",
    concierge_sub: "សំណើតាមតម្រូវការ",
    srv_fasttrack: "ផ្លូវលឿនអាកាសយានដ្ឋាន",
    srv_limo: "រថយន្ត Limousine & Maybach",
    srv_hotel: "បន្ទប់សង្គ្រោះសណ្ឋាគារលំដាប់ផ្កាយ៥",
    srv_diet: "របបអាហារក្រោយការវះកាត់",
    btn_request: "ស្នើសុំ",

    passport_title: "កាបូបវេជ្ជសាស្ត្រ E-Wallet",
    passport_id: "អត្តសញ្ញាណឌីជីថល",
    passport_records: "កំណត់ត្រាវេជ្ជសាស្រ្តសុវត្ថិភាព",
    scan_3d: "ស្កេនផ្ទៃមុខ 3D (វិច្ឆិកា 2026)",
    xray_pano: "កាំរស្មីអ៊ិចប៉ាណូរ៉ាម៉ា",
    tryon_title: "ការវាយតម្លៃ AI និម្មិត",
    tryon_scanning: "កំពុងស្កេនភាពស៊ីមេទ្រី...",
    tryon_sym: "ភាពស៊ីមេទ្រី",
    tryon_age: "អាយុស្បែកប៉ាន់ស្មាន",
    wiz_title: "សេវាកម្មកក់",
    wiz_step1: "ជ្រើសរើសកាលបរិច្ឆេទ",
    wiz_step2: "ភស្តុភារ",
    wiz_step_hotel: "ការស្នាក់នៅ",
    wiz_step3: "អ្នកបកប្រែ",
    wiz_step4: "ហត្ថលេខា",
    wiz_confirm: "បញ្ជាក់ការកក់",
    log_hotel_title: "ស្នើសុំការកក់សណ្ឋាគារ (លំដាប់ផ្កាយ៥)",
    log_hotel_sub: "សណ្ឋាគារប្រណីតជាដៃគូ",
    log_hotel_detail: "យើងនឹងរៀបចំការស្នាក់នៅកម្រិតខ្ពស់នៅសណ្ឋាគារលំដាប់ផ្កាយ ៥ ជាដៃគូរបស់យើង។ រួមបញ្ចូលទាំងសេវាកម្មបន្ទប់ដែលបានកំណត់សម្រាប់វេជ្ជសាស្ត្រ។",
    log_hotel_self_title: "កក់ដោយខ្លួនឯង",
    log_hotel_self_sub: "ការស្នាក់នៅឯករាជ្យ",
    log_hotel_self_detail: "ជ្រើសរើសការស្នាក់នៅផ្ទាល់ខ្លួនរបស់អ្នក។ សូមប្រាកដថាទីតាំងរបស់អ្នកស្ថិតក្នុងរង្វង់ ៣០ នាទីពីគ្លីនិកសម្រាប់ការពិនិត្យក្រោយនីតិវិធី។",
    my_page_title: "ទំព័ររបស់ខ្ញុំ",
    my_points: "ពិន្ទុរបស់ខ្ញុំ",
    my_coupons: "ប័ណ្ណរបស់ខ្ញុំ",
    my_inquiries: "ការសាកសួរ",
    my_level: "Lv.1",
    my_bookings_pay: "ការកក់ និងការទូទាត់",
    my_liked: "បញ្ជីដែលចូលចិត្ត",
    my_benefits: "អត្ថប្រយោជន៍",
    my_reviews: "ការពិនិត្យឡើងវិញ",
    my_notif: "ការជូនដំណឹង",
    my_msgs: "សារ",
    cust_center: "មជ្ឈមណ្ឌលសេវាកម្ម",
    notice: "សេចក្តីជូនដំណឹង",
    settings_title: "ការកំណត់",
    service_info: "ព័ត៌មានសេវាកម្ម",
    version_info: "ព័ត៌មានកំណែ",
    partnership: "ភាពជាដៃគូ និងការផ្សាយពាណិជ្ជកម្ម",
    terms: "លក្ខខណ្ឌនៃសេវាកម្ម",
    privacy: "គោលការណ៍ឯកជនភាព",
    location_terms: "លក្ខខណ្ឌទីតាំង",
    notif_settings: "ការកំណត់ការជូនដំណឹង",
    gen_notif: "ការជូនដំណឹងទូទៅ",
    notes_notif: "ការជូនដំណឹងកំណត់ចំណាំ",
    marketing_info: "ព័ត៌មានទីផ្សារ",
    push: "Push",
    night_push: "ការជូនដំណឹងពេលយប់ (២១:០០ - ០៨:០០)",
    acc_mgmt: "ការគ្រប់គ្រងគណនី",
    logout: "ចាកចេញ",
    delete_acc: "លុបគណនី",
    upload_profile: "បង្ហោះរូបភាពប្រវត្តិរូប",
    confirmed_res: "ការកក់ដែលបានបញ្ជាក់",
    no_bookings: "មិនទាន់មានការកក់ដែលបានបញ្ជាក់នៅឡើយទេ។",
    voice_listening: "កំពុងស្តាប់...",
    voice_tap: "ចុចដើម្បីនិយាយ",

    est_title: "ការប៉ាន់ស្មានតម្លៃ",
    est_sub: "តម្លៃតម្លាភាព",
    est_proc1: "ការប្រឆាំងភាពចាស់",
    est_proc2: "ការព្យាបាលកោសិកាដើម",
    est_proc3: "ការផ្សាំធ្មេញកម្រិតខ្ពស់",
    est_total: "ការចំណាយប៉ាន់ស្មាន",
    ba_title: "ករណីគ្លីនិក",
    ba_sub: "អូសដើម្បីប្រៀបធៀប",
    time_arrive: "ការមកដល់ ICN",
    time_consult: "ការពិគ្រោះយោបល់",
    time_surgery: "នីតិវិធី",
    time_recover: "បន្ទប់សង្គ្រោះ",

    clinics_title: "គ្លីនិក",
    clinics_sub: "ដៃគូផ្លូវការ",
    reviews_count: "ការវាយតម្លៃ",
    clinic_1: "Grand Plastic Surgery",
    clinic_2: "Seoul National Dental",
    proc_1: "ការលើកមុខប្រឆាំងភាពចាស់កោសិកាដើម",
    proc_2: "ការផ្សាំធ្មេញ 3D កម្រិតខ្ពស់ និងធ្វើឱ្យស",
    clinic_3: "The Seoul Breast Clinic",
    clinic_4: "Iconic Rhinoplasty Center",
    proc_3: "ការកែដើមទ្រូងកម្រិត Full HD",
    proc_4: "ការកែទម្រង់ច្រមុះតាមរចនាសម្ព័ន្ធ",
    about_procedure: "អំពីនីតិវិធី",
    duration: "រយៈពេល",
    recovery: "ការងើបឡើងវិញ",
    medical_staff: "បុគ្គលិកពេទ្យ",
    location: "ទីតាំង",
    reserve_now: "កក់ឥឡូវនេះ",
    back_to_list: "ត្រលប់ក្រោយ",
    log_vip_title: "សេវាទទួលនៅស្ថានីយ VIP អាកាសយានដ្ឋាន ICN",
    log_vip_escort: "និងការអមដំណើរ $680",
    log_vip_car: "Maybach S680",
    log_vip_detail: "ការទទួលដោយរថយន្ត Maybach S680 ផ្តាច់មុខដោយផ្ទាល់ពីច្រកទ្វារ VIP របស់ ICN។ រួមបញ្ចូលទាំងការអមដំណើរផ្ទាល់ខ្លួនតាមរយៈអន្តោប្រវេសន៍ សេវាកម្មអ្នកបើកបររយៈពេល ៣ ម៉ោង និងការរៀបចំឥវ៉ាន់។",
    log_self_title: "ការមកដល់ដោយខ្លួនឯង",
    log_self_sub: "ការដឹកជញ្ជូនឯករាជ្យ",
    log_self_detail: "រៀបចំការដឹកជញ្ជូនផ្ទាល់ខ្លួនរបស់អ្នកទៅកាន់គ្លីនិក។ យើងនឹងផ្តល់នូវកូអរដោនេ GPS ច្បាស់លាស់ និងព័ត៌មានទំនាក់ទំនងរបស់អ្នកសម្របសម្រួលវេជ្ជសាស្ត្ររបស់អ្នកនៅពេលមកដល់។"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('EN');

  const t = (key) => {
    return translations[lang][key] || translations['EN'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      <div className={`lang-${lang.toLowerCase()} contents`}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
